#!/bin/zsh

__PVM_SECONDARY_NAME="lein"
__PVM_PORT="3000"

__PVM_IMP_GET_STARTED_URL='https://clojure.org/guides/getting_started'

__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=("echo '(println \"<<HELLOWORLDTEXT>>\")' > hello-world.clj")
__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=("clj -M hello-world.clj")

__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('java -version')
# SOURCE: 16nov2021 https://github.com/clojure-emacs/cider/commit/37acd50
__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('clojure --version')
__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('lein --version')

__PVM_IMP_ALIASES[java]='java'
__PVM_IMP_ALIASES[clj]='clojure'
__PVM_IMP_ALIASES[lein]='lein'
