#!/bin/zsh

__PVM_IMP_GET_STARTED_URL='https://golang.org/doc/tutorial/getting-started'

__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=('go mod init example/hello')
__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=("cat << EOF > hello.go
package main

import \"fmt\"

func main() {
    fmt.Println(\"<<HELLOWORLDTEXT>>\")
}
EOF")
__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=('go run .')

__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('go version')

__PVM_IMP_ALIASES[go]='go'
# DOC: 16nov2021 https://golang.org/doc/install/source#environment
__PVM_IMP_ALIASES[build_for_macos]='env GOOS=darwin GOARCH=amd64 go build'
