#!/bin/zsh

__PVM_SECONDARY_NAME="Ruby on Rails"
__PVM_PORT="3000"

__PVM_IMP_GET_STARTED_URL='http://www.ruby-lang.org/en/documentation/'

__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=("echo 'puts \"<<HELLOWORLDTEXT>>\"' > hello_world.rb")
__PVM_IMP_HOW_TO_HELLO_WORLD_LINES+=("ruby hello_world.rb")

function __pvm_imp_after_docker_dev_img_start() {
  if ! [ -f "${__PVM_HOST_USER_CONFIG_DIR_FULL_PATH}/.bundle/global/bin/rails" ]; then
    if [ -d "${__PVM_HOST_USER_CONFIG_DIR_FULL_PATH}/.bundle" ]; then
      __pvm_echo_error "'${__PVM_HOST_USER_CONFIG_DIR_FULL_PATH}/.bundle' directory is present but 'rails' executable is missing. Something went wrong. Exit and relaunch the env setup."
      return 1
    fi
    print "Copying preinstalled gems into '.bundle' dir..."
    __pvm_docker_dev_img_exec mkdir -p "${__PVM_CONTAINER_USER_CONFIG_DIR_FULL_PATH}/.bundle"
    __pvm_docker_dev_img_exec cp -R /home/preinstalled-gems/ "${__PVM_CONTAINER_USER_CONFIG_DIR_FULL_PATH}/.bundle/global"
    echo
  fi

  if [ -f Gemfile ]; then
    __pvm_print_and_run_command bundle install
    echo
  fi
}

__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('ruby --version')
__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('bundle --version')
__PVM_IMP_COMMANDS_TO_RUN_AT_THE_END+=('rails --version')

__PVM_IMP_ALIASES[ruby]='ruby'
__PVM_IMP_ALIASES[bundle]='bundle'
__PVM_IMP_ALIASES[gem]='gem'
__PVM_IMP_ALIASES[rspec]='rspec'
__PVM_IMP_ALIASES[rails]='rails'
__PVM_IMP_ALIASES[serve]="rails server -p ${__PVM_PORT} -b 0.0.0.0"
